### ISSUE TITLE
Ignore `node_modules` by default

### ISSUE THREAD

**Issue by ehmicky** [ample/netlify-plugin-replace#3]
`node_modules` should not be searched by default. Additionally, it might be good to exclude any directory that is specified in `.gitignore`. There are several libraries providing with this, such as [`node-ignore`](https://github.com/kaelzhang/node-ignore) or [`gitignore-to-glob`](https://github.com/EE/gitignore-to-glob).

This will make this plugin much faster. What do you think?

**Comment by ehmicky** [comment]
Thanks a lot for checking this out @tcmacdonald!

It looks like repositories without a `.gitignore` crash when the following line is performed: 

https://github.com/ample/netlify-plugin-replace/blob/ddb476edffdbbd8ffab8ecb342c09cfa837c75e4/lib/replace.js#L54

Also, `node_modules` is only excluded for repositories with a `.gitignore` (whose content includes `node_modules`). Should it be always excluded from the files search? This might help make this plugin much faster for those repositories, what do you think?

**Comment by tcmacdonald** [comment]
Eeek– not sure how this slipped past me @ehmicky. And yes, I can exclude `node_modules` irrespective of the presence of `.gitignore`. Stand by!
