### ISSUE TITLE
Path Error when integrating with static website

### ISSUE THREAD

**Issue by GuitooStephan** [ample/netlify-plugin-replace#7]
Error message
RangeError: path should be a `path.relative()`d string, but got "/opt/build/repo/assets/main.js"

**Comment by tcmacdonald** [comment]
Thanks for the bug report @GuitooStephan!

Can you share the contents of your `netlify.toml` file and an example build log containing this error? And if your repository is publicly accessible, that would be very helpful too.

**Comment by tcmacdonald** [comment]
@GuitooStephan – I'm closing this issue for now but let me know if this continues to be a problem and we'll reopen. Thanks!
